### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by happyendermangit** [Wumpus-University/HappyCord#1]
## Patches:
- [ ] Fix webpack.push patcher doesnt patch first 1k modules
- [ ] add context menu patches
- [ ] make some apis like (chat textarea buttons, servers list, etc)

## Plugins options
- [ ] Fix dropdown options
- [ ] fix default options not registered

**Comment by happyendermangit** [comment]
Hopefuly i finish it today
